# ********************************************** #
#                                                #
#     -- SoaromaFM Configuration File --         #
#           -- Version 0.0.4 --                  #
#                                                #
# ********************************************** #

# If you are having issues, message me on discord: TheLonelyGamer#5978

# ----------------------------------------------- #
# CHAT FORMAT CONFIGURATION
# ----------------------------------------------- #
# Set the users chat format
# There are multiple placeholders for the default chat format
# All of them are 
# {gender-name}  - Meaning the name of the gender
# {gender-prefix} - Meaning the gender prefix
# {marriage-name} - Meaning the partners name
# {marriage-heart} - Meaning display a heart if married
# user is the player

# please note this plugin uses HEX colour support not default minecraft like &4 or something
# To find a new colour please use this website and put the number inbetween this '#colourcode/ {message}'
# this website you can use ANY colour you want
# https://html-color.codes/



# Family chat format
familyChatFormat: '#6CFFC6/{family} {displayName} #0C1428/>> #00ffef/{message}'

globalChatFormat: '{vault-prefix}{soaroma-prefix}'

# Global chat channel
defaultChatFormat: "#7df9ff/{familyName} {gender-prefix} #ff5349/{marriage-heart} "

# Update display per chat
updateDisplayNameChat: true

# Family prefix chat channel
family-chat-prefix: "#696969/[#ff5349/FM#696969/]"

# Marriage heart-prefix | Linked with defaultChatFormat
heart-prefix: "#ff5349/<3"

# Marriage display name | linked with defaultChatFormat
marriage-name: "#696969/|#ff5349/{partner-name}#696969/|&f"

# Gender prefix | linked with defaultChatFormat
gender-prefix: "{gender-prefix}"

# Gender name | linked with defaultChatFormat
gender-name: "{gender-name}"

# Change users display name
changeDisplayName: true

# ----------------------------------------------- #
# XP SHARE SYSTEM
# ----------------------------------------------- #
# Set the XP share system
# Enable xp sharing
enableXPFamilyShare: true

# Enable message notify of gaining XP
notifyFamilyXPGain: true

# Percentage other family members gain when gaining XP (In percentages)
sharedXPGain: 5.0

# XP Gain message
XPGainMessage: '#39ff14/Gained #ff5349/{xp-amount} xp #39ff14/| a member of your family has gained XP'

# ----------------------------------------------- #
# General Messages
# ----------------------------------------------- #
# Set general messages
# Set marriage proposal
marriageProposal: '#39ff14/Sent a marriage proposal to #ff5349/{name} #39ff14/with the family name of #ff5349/{family-name}'

# Send to proposed player
marriageProposalSend: '#ff5349/{name} #39ff14/sent a proposal to you #39ff14/with the family name of #ff5349/{family-name}#39ff14/, type /fm marry accept {name} to accept'

# Accept marriage proposal
marriageProposalAccept: '#ff5349/{name} #39ff14/has accepted your marriage proposal! Congratulations!'

# Accept marriage proposal
marriageProposalAccepter: '#ff5349/You are now married to #ff5349/{name}#39ff14/! Congratulations!'

# Marriage proposal decline
marriageProposalDecline: '#ff5349/{name} #39ff14/has erm declined your marriage proposal... sorry for your loss..'

# Marriage proposal decline to decliner
marriageProposalDeclineDecliner: '#39ff14/You have declined the proposal of #ff5349/{name}'

# Message when a user declines anothers proposal but the other player didn't propose
marriageProposalDeclineNotProposed: '#39ff14/Specified player did not send you a proposal... lol'

# Marriage divorce
marriageDivorce: '#39ff14/You have um... divorced {user}... ;-;'

# Message to request being a child of a family
childProposalMessage: '#ff5349/{name} #39ff14/has requested to adopt you! Type /fm adopt accept {name} to accept'

# Child acceptance message
childAcceptanceMessage: '#ff5349/{name} #39ff14/has accepted your request to be apart of the family and is now your child!'

# Send message to child which accepted to be apart of the family
childAcceptanceMessageToChild: '#39ff14/You are now the child of {name}!'

# Child request decline message
childDeclineMessage: '#ff5349/{name} #39ff14/has not requested your adoption to be apart of the family... lol'

# Child request decline message
sentAdoptMessage: '#39ff14/Sent adoption message'

# Family leave
leaveFamily: '#39ff14/You have left your family'

# Switch channel to family
switchToFamilyChat: '#39ff14/Switched to family chat'

# Switch channel to global
switchToGlobalChat: '#39ff14/Switched to global chat'

# Same family
sameFamily: '#39ff14/Umm... they are apart of your family... *cough* Alabama'

# Leave your family first
leaveFamilyFirst: '#39ff14/You have to leave your family first, #ff5349//fm familyleave'

who-is-menu:
   - '#39ff14/----- #ff5349/{user} Info #39ff14/-----'
   - '#39ff14/Parents: #ff5349/{parents}'
   - '#39ff14/Siblings: #ff5349/{siblings}'
   - '#39ff14/Married To: #ff5349/{married}'
   - '#39ff14/Gender: #ff5349/{gender}'
   - '#39ff14/Children: #ff5349/{children}'

# Help menu
help-menu:
   - '#39ff14/----- #ff5349/SoaromaFM Help Menu #39ff14/-----'
   - '#ff5349//fm marry {user} {family-name} #39ff14/propose to user'
   - '#ff5349//fm divorce #39ff14/divorces user'
   - '#ff5349//fm marry decline {user} #39ff14/Decline the marriage proposal'
   - '#ff5349//fm help #39ff14/brings up help menu'
   - '#ff5349//fm chat #39ff14/Switch from family to global chat and vice versa'
   - '#ff5349//fm gender {gender} #39ff14/switches gender'
   - '#ff5349//fm genderlist #39ff14/Lists all known genders'
   - '#ff5349//fm removegender #39ff14/Removes gender'
   - '#ff5349//fm familyleave #39ff14/Leaves current family'
   - '#ff5349//fm runaway #39ff14/No longer adopted'
   - '#ff5349//fm adopt {user} #39ff14/Adopt a user'
   - '#ff5349//fm adopt accept {user} #39ff14/Accept an adoption'
   - '#ff5349//fm disown {user} #39ff14/Disowns a child'
   - '#ff5349//fm who {user} #39ff14/Displays family info'
# ----------------------------------------------- #
# Invalid argument messages and no permission
# ----------------------------------------------- #
# Set broadcast options
# Genders
# Invalid argument marriage
invalidArgsMarriage: '#39ff14/Invalid arguments, proper is /fm marry (user) (family-name)'

# Invalid arguments genera
invalidArgsGeneral: '#39ff14/Invalid arguments'

# too long of a family name
tooLongFamilyName: '#39ff14/Mate, way too long of a family name'

# max length a family name can be 
toolongFamilyNameCharLimit: 16

# Invalid argument child
invalidArgsFamily: '#39ff14/Invalid arguments, you are currently not in a family'

# Not married
invalidArgsNotMarried: '#39ff14/You are not married'

# Invalid argument child
invalidArgsAlreadyMarried: '#39ff14/This user is already married'

# Invalid argument gender
invalidArgsGender: '#39ff14/Not a valid gender'

# Invalid argument, taken family name
invalidArgsFamilyNameTaken: '#39ff14/This family name has been taken'

# Not the parent of the family
invalidArgsAlreadyHaveParents: '#39ff14/This user already has parents'

# Tried to marry themselves
invalidArgsPropsalSameUser: '#39ff14/You cannot marry yourself... you are a lonely one... loser'

# Tried to adopt a member of the family
invalidArgsAdoptSameFamily: '#39ff14/They are inside your family!'

# Tried to marry themselves
invalidArgsAdoptSameUser: '#39ff14/You cannot adopt yourself... you are a lonely one... loser'

# Invalid argument child
invalidArgsPlayerNotOnline: '#39ff14/Player is not online'

# Dont have parents
invalidArgsPlayerNoParents: '#39ff14/You do not have any parents... orphan...'

# Accept marriage proposal
invalidMarriageAccept: '#ff5349/{name} #39ff14/has not proposed to you... maybe you should make the first move?'

# No permission
noPermission: '#39ff14/No permission'

# Arent parent
arentParent: '#39ff14/You are not the parent of this user'

# Disowned child
disownedChild: '#39ff14/You have yeeted *cough*.. disowned your child'

# ----------------------------------------------- #
# Broadcast Messages
# ----------------------------------------------- #
# Set broadcast options
# Enable marriage broadcast options : will display to all users which two users got married and the family name
enableMarriageBroadcast: true


# Marriage broadcast message
marriageBroadcastMessage: '#ff5349/{first-user} #39ff14/has married #ff5349/{second-user}#39ff14/ with the family name of #ff5349/{family-name}!'

# Enable divorced broadcasts
enableDivorceBroadcast: true

# Marriage divorce message
marriageDivorceBroadcast: '#ff5349/{first-user} #39ff14/has divorced #ff5349/{second-user}#39ff14/'

# Enable marriage divorce broadcast options : will display to all users which two users got divorced
enableMarriageBroadcast: true

# Enable child acceptance broadcast options : will display to all users which user is now apart of which family
enableChildAcceptanceBroadcast: true

# Now apart of the family message
childAcceptanceBroadcastMessage: '#ff5349/{parent} #39ff14/has adopted #ff5349/{child}'

# Enable child acceptance broadcast options : will display to all users which user is now apart of which family
enableChildLeaveBroadcast: true

# Child acceptance broadcast message
childRunawayBroadcastMessage: '#ff5349/{user} has ran away from their parents!'

# Enable child broadcast disown
enableChildDisownBroadcast: true

childDisownBroadcast: '#ff5349/{user} #39ff14/has disowned #ff5349/{child}'

# ----------------------------------------------- #
# Genders List With Prefix
# ----------------------------------------------- #
# Set broadcast options
# Genders
# Note that the first name for "GENDERS" is also the same for "GENDER-PREFIX"
genders:
   - 'Male'
   - 'Female'
   - 'Apache'
genders-prefix:
   - '&b♂'
   - '&c♀'
   - 'o---/===\-'
   
# Gender change message
genderChangeMessage: '#39ff14/Gender set to {gender}'

# List all known genders
genderList: '#39ff14/Known genders are: {genders}'

# Remove gender
genderRemove: '#39ff14/Removed your gender'
# ----------------------------------------------- #
