name: SoaromaFM
version: 0.0.1
description: Its a family roleplay plugin... with marriage and kids and uh stuff...
author: Korbsti
main: me.korbsti.soaromafm.SoaromaFM
api-version: 1.16
depend: [Vault]
commands:
   fm: